id = "gruva-theme"
name = "Gruva Theme"
schema_version = 1
version = "0.0.1"
authors = ["Benjamin ZubaÄa <bzubaca123@gmail.com>"]
description = "TODO: Add a description"
repository = "https://github.com/bentduso/gruva-zed"
